### Загрузка данных и импортирование библиотеки `pandas`

In [1]:
import pandas as pd

# Создаем словарь с данными о собаках (20 записей)
data = {
    'Name': ['Сноу', 'Рекс', 'Макс', 'Луна', 'Джек', 'Мило', 'Бэйли', 'Лола', 'Тедди', 'Макс',
             'Бентли', 'Джесси', 'Чарли', 'Максимус', 'Оливер', 'Чарли', 'Луи', 'Белль', 'Сади', 'Сэнди'],
    'Breed': ['Лабрадор', 'Бульдог', 'Далматин', 'Ши-тцу', 'Йоркширский терьер', 'Лабрадор', 'Чихуахуа', 'Шарпей', 'Бассет-хаунд', 'Померанский',
              'Золотистый ретривер', 'Бордер-колли', 'Боксер', 'Ротвейлер', 'Доберман', 'Шиба-ину', 'Бостон-терьер', 'Френч бульдог', 'Хаски', 'Акита'],
    'Color': ['Шоколадный', 'Палевый', 'Черно-белый', 'Белый', 'Серый', 'Абрикосовый', 'Черный', 'Коричневый', 'Трехцветный', 'Оранжевый',
              'Золотистый', 'Черно-белый', 'Тигровый', 'Черный и рыжий', 'Черный и коричневый', 'Трехцветный', 'Черно-белый', 'Белый', 'Серо-белый', 'Коричневый'],
    'Height (cm)': [60, 40, 55, 25, 20, 58, 20, 40, 30, 25, 60, 50, 55, 70, 45, 30, 25, 35, 45, 60],
    'Weight (kg)': [30, 25, 20, 5, 3, 27, 3, 15, 10, 4, 25, 18, 30, 40, 12, 6, 5, 8, 12, 30],
    'Date of Birth': ['2015-02-10', '2018-06-05', '2017-11-20', '2019-04-15', '2020-09-30',
                      '2016-03-25', '2019-08-12', '2018-01-03', '2020-05-19', '2017-09-28',
                      '2016-07-14', '2019-02-08', '2017-04-22', '2015-09-07', '2016-12-30',
                      '2018-11-17', '2020-03-08', '2019-10-12', '2016-06-23', '2015-08-02']
}

# Создаем датафрейм из словаря
dogs = pd.DataFrame(data)

# Выводим датафрейм
print(dogs)

        Name                Breed                Color  Height (cm)  \
0       Сноу             Лабрадор           Шоколадный           60
1       Рекс              Бульдог              Палевый           40
2       Макс             Далматин          Черно-белый           55
3       Луна               Ши-тцу                Белый           25
4       Джек   Йоркширский терьер                Серый           20
5       Мило             Лабрадор          Абрикосовый           58
6      Бэйли             Чихуахуа               Черный           20
7       Лола               Шарпей           Коричневый           40
8      Тедди         Бассет-хаунд          Трехцветный           30
9       Макс          Померанский            Оранжевый           25
10    Бентли  Золотистый ретривер           Золотистый           60
11    Джесси         Бордер-колли          Черно-белый           50
12     Чарли               Боксер             Тигровый           55
13  Максимус            Ротвейлер       Черный и рыжий           70
14    Оливер             Доберман  Черный и коричневый           45
15     Чарли             Шиба-ину          Трехцветный           30
16       Луи        Бостон-терьер          Черно-белый           25
17     Белль        Френч бульдог                Белый           35
18      Сади                Хаски           Серо-белый           45
19     Сэнди                Акита           Коричневый           60

    Weight (kg) Date of Birth
0            30    2015-02-10
1            25    2018-06-05
2            20    2017-11-20
3             5    2019-04-15
4             3    2020-09-30
5            27    2016-03-25
6             3    2019-08-12
7            15    2018-01-03
8            10    2020-05-19
9             4    2017-09-28
10           25    2016-07-14
11           18    2019-02-08
12           30    2017-04-22
13           40    2015-09-07
14           12    2016-12-30
15            6    2018-11-17
16            5    2020-03-08
17            8    2019-10-12
18           12    2016-06-23
19           30    2015-08-02

#### Обзор датафрейма

In [6]:
print(dogs.head())

   Name               Breed        Color  Height (cm)  Weight (kg)  \
0  Сноу            Лабрадор   Шоколадный           60           30
1  Рекс             Бульдог      Палевый           40           25
2  Макс            Далматин  Черно-белый           55           20
3  Луна              Ши-тцу        Белый           25            5
4  Джек  Йоркширский терьер        Серый           20            3

  Date of Birth
0    2015-02-10
1    2018-06-05
2    2017-11-20
3    2019-04-15
4    2020-09-30

In [5]:
dogs.head()

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10
1,Рекс,Бульдог,Палевый,40,25,2018-06-05
2,Макс,Далматин,Черно-белый,55,20,2017-11-20
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30

In [7]:
dogs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           20 non-null     object
 1   Breed          20 non-null     object
 2   Color          20 non-null     object
 3   Height (cm)    20 non-null     int64
 4   Weight (kg)    20 non-null     int64
 5   Date of Birth  20 non-null     object
dtypes: int64(2), object(4)
memory usage: 1.1+ KB

In [8]:
dogs.shape

(20, 6)

In [9]:
dogs.values

array([['Сноу', 'Лабрадор', 'Шоколадный', 60, 30, '2015-02-10'],
       ['Рекс', 'Бульдог', 'Палевый', 40, 25, '2018-06-05'],
       ['Макс', 'Далматин', 'Черно-белый', 55, 20, '2017-11-20'],
       ['Луна', 'Ши-тцу', 'Белый', 25, 5, '2019-04-15'],
       ['Джек', 'Йоркширский терьер', 'Серый', 20, 3, '2020-09-30'],
       ['Мило', 'Лабрадор', 'Абрикосовый', 58, 27, '2016-03-25'],
       ['Бэйли', 'Чихуахуа', 'Черный', 20, 3, '2019-08-12'],
       ['Лола', 'Шарпей', 'Коричневый', 40, 15, '2018-01-03'],
       ['Тедди', 'Бассет-хаунд', 'Трехцветный', 30, 10, '2020-05-19'],
       ['Макс', 'Померанский', 'Оранжевый', 25, 4, '2017-09-28'],
       ['Бентли', 'Золотистый ретривер', 'Золотистый', 60, 25,
        '2016-07-14'],
       ['Джесси', 'Бордер-колли', 'Черно-белый', 50, 18, '2019-02-08'],
       ['Чарли', 'Боксер', 'Тигровый', 55, 30, '2017-04-22'],
       ['Максимус', 'Ротвейлер', 'Черный и рыжий', 70, 40, '2015-09-07'],
       ['Оливер', 'Доберман', 'Черный и коричневый', 45, 12,
        '2016-12-30'],
       ['Чарли', 'Шиба-ину', 'Трехцветный', 30, 6, '2018-11-17'],
       ['Луи', 'Бостон-терьер', 'Черно-белый', 25, 5, '2020-03-08'],
       ['Белль', 'Френч бульдог', 'Белый', 35, 8, '2019-10-12'],
       ['Сади', 'Хаски', 'Серо-белый', 45, 12, '2016-06-23'],
       ['Сэнди', 'Акита', 'Коричневый', 60, 30, '2015-08-02']],
      dtype=object)

In [10]:
dogs.describe()

       Height (cm)  Weight (kg)
count    20.000000    20.000000
mean     42.400000    16.400000
std      15.574608    11.287627
min      20.000000     3.000000
25%      28.750000     5.750000
50%      42.500000    13.500000
75%      55.750000    25.500000
max      70.000000    40.000000

In [11]:
dogs.columns

Index(['Name', 'Breed', 'Color', 'Height (cm)', 'Weight (kg)',
       'Date of Birth'],
      dtype='object')

In [12]:
dogs.index

RangeIndex(start=0, stop=20, step=1)

#### Сортировка и выборка

In [13]:
dogs.sort_values("Weight (kg)")

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30
6,Бэйли,Чихуахуа,Черный,20,3,2019-08-12
9,Макс,Померанский,Оранжевый,25,4,2017-09-28
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
16,Луи,Бостон-терьер,Черно-белый,25,5,2020-03-08
15,Чарли,Шиба-ину,Трехцветный,30,6,2018-11-17
17,Белль,Френч бульдог,Белый,35,8,2019-10-12
8,Тедди,Бассет-хаунд,Трехцветный,30,10,2020-05-19
18,Сади,Хаски,Серо-белый,45,12,2016-06-23
14,Оливер,Доберман,Черный и коричневый,45,12,2016-12-30
7,Лола,Шарпей,Коричневый,40,15,2018-01-03
11,Джесси,Бордер-колли,Черно-белый,50,18,2019-02-08
2,Макс,Далматин,Черно-белый,55,20,2017-11-20
1,Рекс,Бульдог,Палевый,40,25,2018-06-05
10,Бентли,Золотистый ретривер,Золотистый,60,25,2016-07-14
5,Мило,Лабрадор,Абрикосовый,58,27,2016-03-25
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10
12,Чарли,Боксер,Тигровый,55,30,2017-04-22
19,Сэнди,Акита,Коричневый,60,30,2015-08-02
13,Максимус,Ротвейлер,Черный и рыжий,70,40,2015-09-07

In [14]:
dogs.sort_values("Weight (kg)", ascending=False)

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
13,Максимус,Ротвейлер,Черный и рыжий,70,40,2015-09-07
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10
12,Чарли,Боксер,Тигровый,55,30,2017-04-22
19,Сэнди,Акита,Коричневый,60,30,2015-08-02
5,Мило,Лабрадор,Абрикосовый,58,27,2016-03-25
1,Рекс,Бульдог,Палевый,40,25,2018-06-05
10,Бентли,Золотистый ретривер,Золотистый,60,25,2016-07-14
2,Макс,Далматин,Черно-белый,55,20,2017-11-20
11,Джесси,Бордер-колли,Черно-белый,50,18,2019-02-08
7,Лола,Шарпей,Коричневый,40,15,2018-01-03
14,Оливер,Доберман,Черный и коричневый,45,12,2016-12-30
18,Сади,Хаски,Серо-белый,45,12,2016-06-23
8,Тедди,Бассет-хаунд,Трехцветный,30,10,2020-05-19
17,Белль,Френч бульдог,Белый,35,8,2019-10-12
15,Чарли,Шиба-ину,Трехцветный,30,6,2018-11-17
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
16,Луи,Бостон-терьер,Черно-белый,25,5,2020-03-08
9,Макс,Померанский,Оранжевый,25,4,2017-09-28
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30
6,Бэйли,Чихуахуа,Черный,20,3,2019-08-12

In [16]:
dogs.sort_values(["Weight (kg)", "Height (cm)"])

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30
6,Бэйли,Чихуахуа,Черный,20,3,2019-08-12
9,Макс,Померанский,Оранжевый,25,4,2017-09-28
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
16,Луи,Бостон-терьер,Черно-белый,25,5,2020-03-08
15,Чарли,Шиба-ину,Трехцветный,30,6,2018-11-17
17,Белль,Френч бульдог,Белый,35,8,2019-10-12
8,Тедди,Бассет-хаунд,Трехцветный,30,10,2020-05-19
14,Оливер,Доберман,Черный и коричневый,45,12,2016-12-30
18,Сади,Хаски,Серо-белый,45,12,2016-06-23
7,Лола,Шарпей,Коричневый,40,15,2018-01-03
11,Джесси,Бордер-колли,Черно-белый,50,18,2019-02-08
2,Макс,Далматин,Черно-белый,55,20,2017-11-20
1,Рекс,Бульдог,Палевый,40,25,2018-06-05
10,Бентли,Золотистый ретривер,Золотистый,60,25,2016-07-14
5,Мило,Лабрадор,Абрикосовый,58,27,2016-03-25
12,Чарли,Боксер,Тигровый,55,30,2017-04-22
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10
19,Сэнди,Акита,Коричневый,60,30,2015-08-02
13,Максимус,Ротвейлер,Черный и рыжий,70,40,2015-09-07

In [17]:
dogs.sort_values(["Weight (kg)", "Height (cm)"], ascending=[True, False])

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30
6,Бэйли,Чихуахуа,Черный,20,3,2019-08-12
9,Макс,Померанский,Оранжевый,25,4,2017-09-28
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
16,Луи,Бостон-терьер,Черно-белый,25,5,2020-03-08
15,Чарли,Шиба-ину,Трехцветный,30,6,2018-11-17
17,Белль,Френч бульдог,Белый,35,8,2019-10-12
8,Тедди,Бассет-хаунд,Трехцветный,30,10,2020-05-19
14,Оливер,Доберман,Черный и коричневый,45,12,2016-12-30
18,Сади,Хаски,Серо-белый,45,12,2016-06-23
7,Лола,Шарпей,Коричневый,40,15,2018-01-03
11,Джесси,Бордер-колли,Черно-белый,50,18,2019-02-08
2,Макс,Далматин,Черно-белый,55,20,2017-11-20
10,Бентли,Золотистый ретривер,Золотистый,60,25,2016-07-14
1,Рекс,Бульдог,Палевый,40,25,2018-06-05
5,Мило,Лабрадор,Абрикосовый,58,27,2016-03-25
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10
19,Сэнди,Акита,Коричневый,60,30,2015-08-02
12,Чарли,Боксер,Тигровый,55,30,2017-04-22
13,Максимус,Ротвейлер,Черный и рыжий,70,40,2015-09-07

In [18]:
dogs["Name"]

0         Сноу
1         Рекс
2         Макс
3         Луна
4         Джек
5         Мило
6        Бэйли
7         Лола
8        Тедди
9         Макс
10      Бентли
11      Джесси
12       Чарли
13    Максимус
14      Оливер
15       Чарли
16         Луи
17       Белль
18        Сади
19       Сэнди
Name: Name, dtype: object

In [20]:
dogs[["Name", "Height (cm)"]]

        Name  Height (cm)
0       Сноу           60
1       Рекс           40
2       Макс           55
3       Луна           25
4       Джек           20
5       Мило           58
6      Бэйли           20
7       Лола           40
8      Тедди           30
9       Макс           25
10    Бентли           60
11    Джесси           50
12     Чарли           55
13  Максимус           70
14    Оливер           45
15     Чарли           30
16       Луи           25
17     Белль           35
18      Сади           45
19     Сэнди           60

In [22]:
dogs[dogs["Height (cm)"] > 50]

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10
2,Макс,Далматин,Черно-белый,55,20,2017-11-20
5,Мило,Лабрадор,Абрикосовый,58,27,2016-03-25
10,Бентли,Золотистый ретривер,Золотистый,60,25,2016-07-14
12,Чарли,Боксер,Тигровый,55,30,2017-04-22
13,Максимус,Ротвейлер,Черный и рыжий,70,40,2015-09-07
19,Сэнди,Акита,Коричневый,60,30,2015-08-02

In [23]:
dogs[dogs["Breed"] == "Лабрадор"]

   Name     Breed        Color  Height (cm)  Weight (kg) Date of Birth
0  Сноу  Лабрадор   Шоколадный           60           30    2015-02-10
5  Мило  Лабрадор  Абрикосовый           58           27    2016-03-25

In [24]:
dogs[dogs["Date of Birth"] > "2019-01-01"]

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30
6,Бэйли,Чихуахуа,Черный,20,3,2019-08-12
8,Тедди,Бассет-хаунд,Трехцветный,30,10,2020-05-19
11,Джесси,Бордер-колли,Черно-белый,50,18,2019-02-08
16,Луи,Бостон-терьер,Черно-белый,25,5,2020-03-08
17,Белль,Френч бульдог,Белый,35,8,2019-10-12

In [30]:
is_small = dogs["Height (cm)"] < 40
is_black = dogs["Color"] == 'Черный'
dogs[is_small & is_black] # print()
dogs[is_small | is_black] # print()

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth
3,Луна,Ши-тцу,Белый,25,5,2019-04-15
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30
6,Бэйли,Чихуахуа,Черный,20,3,2019-08-12
8,Тедди,Бассет-хаунд,Трехцветный,30,10,2020-05-19
9,Макс,Померанский,Оранжевый,25,4,2017-09-28
15,Чарли,Шиба-ину,Трехцветный,30,6,2018-11-17
16,Луи,Бостон-терьер,Черно-белый,25,5,2020-03-08
17,Белль,Френч бульдог,Белый,35,8,2019-10-12

In [32]:
is_black_or_white = dogs['Color'].isin(['Черный', 'Белый'])
dogs[is_black_or_white]

     Name          Breed   Color  Height (cm)  Weight (kg) Date of Birth
3    Луна         Ши-тцу   Белый           25            5    2019-04-15
6   Бэйли       Чихуахуа  Черный           20            3    2019-08-12
17  Белль  Френч бульдог   Белый           35            8    2019-10-12

#### Создание новых столбцов

In [33]:
dogs["Height (m)"] = dogs['Height (cm)'] / 100

In [34]:
dogs.head()

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth,Height (m)
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10,0.60
1,Рекс,Бульдог,Палевый,40,25,2018-06-05,0.40
2,Макс,Далматин,Черно-белый,55,20,2017-11-20,0.55
3,Луна,Ши-тцу,Белый,25,5,2019-04-15,0.25
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30,0.20

In [35]:
dogs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           20 non-null     object
 1   Breed          20 non-null     object
 2   Color          20 non-null     object
 3   Height (cm)    20 non-null     int64
 4   Weight (kg)    20 non-null     int64
 5   Date of Birth  20 non-null     object
 6   Height (m)     20 non-null     float64
dtypes: float64(1), int64(2), object(4)
memory usage: 1.2+ KB

In [40]:
print(0.1 + 0.1 == 0.2)
print(0.1 + 0.1 + 0.1 == 0.3) # 13 + 19 = 32 | 1101 + 10011 = 100000 | 0.25 = 2^-2 | 0.1 = ??? | 0.10000000002

True
False

In [41]:
dogs["BMI"] = dogs["Weight (kg)"] / dogs["Height (m)"] ** 2
dogs.head()

,Name,Breed,Color,Height (cm),Weight (kg),Date of Birth,Height (m),BMI
0,Сноу,Лабрадор,Шоколадный,60,30,2015-02-10,0.60,83.333333
1,Рекс,Бульдог,Палевый,40,25,2018-06-05,0.40,156.250000
2,Макс,Далматин,Черно-белый,55,20,2017-11-20,0.55,66.115702
3,Луна,Ши-тцу,Белый,25,5,2019-04-15,0.25,80.000000
4,Джек,Йоркширский терьер,Серый,20,3,2020-09-30,0.20,75.000000

#### Сводная статистика

In [42]:
dogs.describe()

       Height (cm)  Weight (kg)  Height (m)         BMI
count    20.000000    20.000000   20.000000   20.000000
mean     42.400000    16.400000    0.424000   81.044852
std      15.574608    11.287627    0.155746   22.088353
min      20.000000     3.000000    0.200000   59.259259
25%      28.750000     5.750000    0.287500   66.528926
50%      42.500000    13.500000    0.425000   77.500000
75%      55.750000    25.500000    0.557500   83.333333
max      70.000000    40.000000    0.700000  156.250000

In [43]:
dogs['Height (cm)'].mean()

42.4

In [44]:
dogs['Height (cm)'].median()

42.5

In [45]:
dogs['Height (cm)'].mode()

0    25
1    60
Name: Height (cm), dtype: int64

In [46]:
dogs['Height (cm)'].min()

20

In [47]:
dogs['Height (cm)'].max()

70

In [48]:
dogs['Height (cm)'].var()

242.56842105263158

In [49]:
dogs['Height (cm)'].sum()

848

In [51]:
dogs['Height (cm)'].quantile(0.51)

43.449999999999996

In [52]:
dogs['Date of Birth'].min()

'2015-02-10'

In [53]:
dogs['Date of Birth'].max()

'2020-09-30'

In [54]:
def pct30(column):
    return column.quantile(0.3)

dogs["Weight (kg)"].agg(pct30)

7.4

In [56]:
def pct40(column):
    return column.quantile(0.4)

dogs[["Weight (kg)", "Height (cm)"]].agg([pct30, pct40])

       Weight (kg)  Height (cm)
pct30          7.4         30.0
pct40         11.2         38.0

In [57]:
dogs["Weight (kg)"].cumsum()

0      30
1      55
2      75
3      80
4      83
5     110
6     113
7     128
8     138
9     142
10    167
11    185
12    215
13    255
14    267
15    273
16    278
17    286
18    298
19    328
Name: Weight (kg), dtype: int64

In [66]:
import random
import datetime
random.seed(42)
# Генерируем дополнительные записи (в данном случае, добавим 55 дополнительных записей)
vet_visits = {
    'Name': [random.choice(data['Name']) for _ in range(75)],
    'Breed': [random.choice(data['Breed']) for _ in range(75)],
    'Color': [random.choice(data['Color']) for _ in range(75)],
    'Height (cm)': [random.randint(20, 70) for _ in range(75)],
    'Weight (kg)': [random.randint(3, 40) for _ in range(75)],
    'Date of Birth': [f"{random.randint(2015, 2022)}-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}" for _ in range(75)],
    'Visit Date': [datetime.date(2023, random.randint(1, 9), random.randint(1, 28)) for _ in range(75)]
}

In [68]:
vet_visits = pd.DataFrame(vet_visits)
vet_visits = vet_visits[['Visit Date', 'Name', 'Breed', 'Weight (kg)']]
vet_visits

    Visit Date   Name               Breed  Weight (kg)
0   2023-02-05   Луна              Шарпей           35
1   2023-03-08   Сноу            Лабрадор           36
2   2023-07-23  Тедди            Доберман           13
3   2023-03-23   Лола              Боксер            6
4   2023-04-03   Лола        Бассет-хаунд           35
..         ...    ...                 ...          ...
70  2023-03-24  Тедди       Бостон-терьер           34
71  2023-09-21   Макс               Акита           19
72  2023-05-20  Сэнди            Чихуахуа            6
73  2023-09-25   Мило  Йоркширский терьер            8
74  2023-08-15  Белль        Бордер-колли           30

[75 rows x 4 columns]

In [69]:
vet_visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Visit Date   75 non-null     object
 1   Name         75 non-null     object
 2   Breed        75 non-null     object
 3   Weight (kg)  75 non-null     int64
dtypes: int64(1), object(3)
memory usage: 2.5+ KB

In [70]:
vet_visits.drop_duplicates(subset="Name")

    Visit Date      Name                Breed  Weight (kg)
0   2023-02-05      Луна               Шарпей           35
1   2023-03-08      Сноу             Лабрадор           36
2   2023-07-23     Тедди             Доберман           13
3   2023-03-23      Лола               Боксер            6
5   2023-07-14      Джек        Френч бульдог            8
7   2023-08-14     Белль  Золотистый ретривер            7
8   2023-01-07      Макс              Бульдог            7
9   2023-07-13      Сади               Шарпей           18
10  2023-01-28  Максимус              Бульдог           28
11  2023-07-16      Рекс  Золотистый ретривер           10
14  2023-07-28     Бэйли             Далматин           40
16  2023-09-26       Луи                Хаски            8
17  2023-04-16     Сэнди  Золотистый ретривер           29
24  2023-08-05    Оливер   Йоркширский терьер           23
28  2023-07-05      Мило         Бассет-хаунд           11
30  2023-01-09    Бентли            Ротвейлер           32
37  2023-01-24     Чарли             Шиба-ину            7
39  2023-06-08    Джесси              Бульдог           16

In [71]:
vet_visits.drop_duplicates(subset=["Name", 'Breed'])

    Visit Date   Name               Breed  Weight (kg)
0   2023-02-05   Луна              Шарпей           35
1   2023-03-08   Сноу            Лабрадор           36
2   2023-07-23  Тедди            Доберман           13
3   2023-03-23   Лола              Боксер            6
4   2023-04-03   Лола        Бассет-хаунд           35
..         ...    ...                 ...          ...
69  2023-03-14  Бэйли         Померанский           35
70  2023-03-24  Тедди       Бостон-терьер           34
72  2023-05-20  Сэнди            Чихуахуа            6
73  2023-09-25   Мило  Йоркширский терьер            8
74  2023-08-15  Белль        Бордер-колли           30

[66 rows x 4 columns]

In [ ]:
vet_visits.drop_duplicates(subset=["Name", 'Breed', 'Weight (kg)']) # Излишнее удаление

    Visit Date   Name               Breed  Weight (kg)
0   2023-02-05   Луна              Шарпей           35
1   2023-03-08   Сноу            Лабрадор           36
2   2023-07-23  Тедди            Доберман           13
3   2023-03-23   Лола              Боксер            6
4   2023-04-03   Лола        Бассет-хаунд           35
..         ...    ...                 ...          ...
70  2023-03-24  Тедди       Бостон-терьер           34
71  2023-09-21   Макс               Акита           19
72  2023-05-20  Сэнди            Чихуахуа            6
73  2023-09-25   Мило  Йоркширский терьер            8
74  2023-08-15  Белль        Бордер-колли           30

[73 rows x 4 columns]

In [73]:
unique_dogs = vet_visits.drop_duplicates(subset=["Name", 'Breed'])

In [74]:
unique_dogs['Breed'].value_counts()

Breed
Боксер                 6
Бассет-хаунд           6
Йоркширский терьер     5
Френч бульдог          5
Лабрадор               5
Золотистый ретривер    4
Шарпей                 3
Ши-тцу                 3
Бостон-терьер          3
Ротвейлер              3
Чихуахуа               3
Хаски                  3
Далматин               3
Бульдог                3
Доберман               3
Шиба-ину               2
Бордер-колли           2
Акита                  2
Померанский            2
Name: count, dtype: int64

In [75]:
unique_dogs['Breed'].value_counts(normalize=True).sort_index()

Breed
Акита                  0.030303
Бассет-хаунд           0.090909
Боксер                 0.090909
Бордер-колли           0.030303
Бостон-терьер          0.045455
Бульдог                0.045455
Далматин               0.045455
Доберман               0.045455
Золотистый ретривер    0.060606
Йоркширский терьер     0.075758
Лабрадор               0.075758
Померанский            0.030303
Ротвейлер              0.045455
Френч бульдог          0.075758
Хаски                  0.045455
Чихуахуа               0.045455
Шарпей                 0.045455
Ши-тцу                 0.045455
Шиба-ину               0.030303
Name: proportion, dtype: float64

#### Сводная статистика сгруппированных данных

In [76]:
dogs[dogs['Color']=='Шоколадный']['Weight (kg)'].mean()

30.0

In [77]:
dogs[dogs['Color']=='Черно-белый']['Weight (kg)'].mean()

14.333333333333334

In [78]:
dogs.groupby('Color')['Weight (kg)'].mean()

Color
Абрикосовый            27.000000
Белый                   6.500000
Золотистый             25.000000
Коричневый             22.500000
Оранжевый               4.000000
Палевый                25.000000
Серо-белый             12.000000
Серый                   3.000000
Тигровый               30.000000
Трехцветный             8.000000
Черно-белый            14.333333
Черный                  3.000000
Черный и коричневый    12.000000
Черный и рыжий         40.000000
Шоколадный             30.000000
Name: Weight (kg), dtype: float64

In [80]:
dogs.groupby('Color')['Weight (kg)'].agg(["min", "max", "sum"])

                     min  max  sum
Color
Абрикосовый           27   27   27
Белый                  5    8   13
Золотистый            25   25   25
Коричневый            15   30   45
Оранжевый              4    4    4
Палевый               25   25   25
Серо-белый            12   12   12
Серый                  3    3    3
Тигровый              30   30   30
Трехцветный            6   10   16
Черно-белый            5   20   43
Черный                 3    3    3
Черный и коричневый   12   12   12
Черный и рыжий        40   40   40
Шоколадный            30   30   30

In [81]:
dogs.groupby(['Color', 'Breed'])['Weight (kg)'].mean()

Color                Breed
Абрикосовый          Лабрадор               27.0
Белый                Френч бульдог           8.0
                     Ши-тцу                  5.0
Золотистый           Золотистый ретривер    25.0
Коричневый           Акита                  30.0
                     Шарпей                 15.0
Оранжевый            Померанский             4.0
Палевый              Бульдог                25.0
Серо-белый           Хаски                  12.0
Серый                Йоркширский терьер      3.0
Тигровый             Боксер                 30.0
Трехцветный          Бассет-хаунд           10.0
                     Шиба-ину                6.0
Черно-белый          Бордер-колли           18.0
                     Бостон-терьер           5.0
                     Далматин               20.0
Черный               Чихуахуа                3.0
Черный и коричневый  Доберман               12.0
Черный и рыжий       Ротвейлер              40.0
Шоколадный           Лабрадор               30.0
Name: Weight (kg), dtype: float64

In [83]:
dogs.groupby(['Color', 'Breed'])[['Weight (kg)', 'Height (cm)']].mean()

                                         Weight (kg)  Height (cm)
Color               Breed
Абрикосовый         Лабрадор                    27.0         58.0
Белый               Френч бульдог                8.0         35.0
                    Ши-тцу                       5.0         25.0
Золотистый          Золотистый ретривер         25.0         60.0
Коричневый          Акита                       30.0         60.0
                    Шарпей                      15.0         40.0
Оранжевый           Померанский                  4.0         25.0
Палевый             Бульдог                     25.0         40.0
Серо-белый          Хаски                       12.0         45.0
Серый               Йоркширский терьер           3.0         20.0
Тигровый            Боксер                      30.0         55.0
Трехцветный         Бассет-хаунд                10.0         30.0
                    Шиба-ину                     6.0         30.0
Черно-белый         Бордер-колли                18.0         50.0
                    Бостон-терьер                5.0         25.0
                    Далматин                    20.0         55.0
Черный              Чихуахуа                     3.0         20.0
Черный и коричневый Доберман                    12.0         45.0
Черный и рыжий      Ротвейлер                   40.0         70.0
Шоколадный          Лабрадор                    30.0         60.0

In [84]:
dogs.pivot_table(values='Weight (kg)', index='Color')

                     Weight (kg)
Color
Абрикосовый            27.000000
Белый                   6.500000
Золотистый             25.000000
Коричневый             22.500000
Оранжевый               4.000000
Палевый                25.000000
Серо-белый             12.000000
Серый                   3.000000
Тигровый               30.000000
Трехцветный             8.000000
Черно-белый            14.333333
Черный                  3.000000
Черный и коричневый    12.000000
Черный и рыжий         40.000000
Шоколадный             30.000000

In [ ]:
def karatsuba(x, y):
    """
    x, y: неотрицательные целые числа
    Возвращает произведение x * y по алгоритму Карацубы.
    """
    n = max(x.bit_length(), y.bit_length())

    if n <= 1:
        return x * y

    half = n // 2

    x_l = x >> half
    x_r = x - (x_l << half)

    y_l = y >> half
    y_r = y - (y_l << half)

    p_1 = karatsuba(x_l, y_l)
    p_2 = karatsuba(x_r, y_r)
    p_3 = karatsuba(x_l + x_r, y_l + y_r)

    return (p_1 << (2 * half)) + ((p_3 - p_1 - p_2) << half) + p_2