In [1]:
!pip3 install nltk

Requirement already satisfied: nltk in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (3.9.1)
Requirement already satisfied: click in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from nltk) (4.67.1)

In [2]:
import numpy as np
import pandas as pd
import re
import nltk
import string

In [3]:
full_df = pd.read_csv('tweet_small.csv')

In [4]:
full_df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0

In [5]:
df = full_df[["text"]]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    93 non-null     object
dtypes: object(1)
memory usage: 876.0+ bytes

In [6]:
print(df)

                                                 text
0   @AppleSupport causing the reply to be disregar...
1   @105835 Your business means a lot to us. Pleas...
2   @76328 I really hope you all change but I'm su...
3   @105836 LiveChat is online at the moment - htt...
4   @VirginTrains see attached error message. I've...
..                                                ...
88  @105860 I wish Amazon had an option of where I...
89  They reschedule my shit for tomorrow https://t...
90  @105861 Hey Sara, sorry to hear of the issues ...
91  @Tesco bit of both - finding the layout cumber...
92  @105861 If that doesn't help please DM your fu...

[93 rows x 1 columns]

#### Перевод к нижнему регистру

In [7]:
df['text_lower'] = df['text'].str.lower()
print(df)

                                                 text  \
0   @AppleSupport causing the reply to be disregar...
1   @105835 Your business means a lot to us. Pleas...
2   @76328 I really hope you all change but I'm su...
3   @105836 LiveChat is online at the moment - htt...
4   @VirginTrains see attached error message. I've...
..                                                ...
88  @105860 I wish Amazon had an option of where I...
89  They reschedule my shit for tomorrow https://t...
90  @105861 Hey Sara, sorry to hear of the issues ...
91  @Tesco bit of both - finding the layout cumber...
92  @105861 If that doesn't help please DM your fu...

                                           text_lower
0   @applesupport causing the reply to be disregar...
1   @105835 your business means a lot to us. pleas...
2   @76328 i really hope you all change but i'm su...
3   @105836 livechat is online at the moment - htt...
4   @virgintrains see attached error message. i've...
..                                                ...
88  @105860 i wish amazon had an option of where i...
89  they reschedule my shit for tomorrow https://t...
90  @105861 hey sara, sorry to hear of the issues ...
91  @tesco bit of both - finding the layout cumber...
92  @105861 if that doesn't help please dm your fu...

[93 rows x 2 columns]

/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_99471/554993334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_lower'] = df['text'].str.lower()

#### Удаление с пунктуации

In [8]:
PUNCT_TO_REMOVE = string.punctuation
def remove_punct(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["text_wo_punct"] = df["text_lower"].apply(remove_punct)
df.head(10)

/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_99471/3834157327.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_wo_punct"] = df["text_lower"].apply(remove_punct)

,text,text_lower,text_wo_punct
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...
5,"@105836 Have you tried from another device, Mi...","@105836 have you tried from another device, mi...",105836 have you tried from another device miri...
6,"@VirginTrains yep, I've tried laptop too sever...","@virgintrains yep, i've tried laptop too sever...",virgintrains yep ive tried laptop too several ...
7,"@105836 It's working OK from here, Miriam. Doe...","@105836 it's working ok from here, miriam. doe...",105836 its working ok from here miriam does th...
8,@VirginTrains I still haven't heard &amp; the ...,@virgintrains i still haven't heard &amp; the ...,virgintrains i still havent heard amp the numb...
9,@105836 That's what we're here for Miriam 😊 T...,@105836 that's what we're here for miriam 😊 t...,105836 thats what were here for miriam 😊 the ...

#### Удаление стоп-слов

In [9]:
from nltk.corpus import stopwords
nltk.download('stopwords')
print(', '.join(stopwords.words('english')))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/artemgolubnichiy/nltk_data...

a, about, above, after, again, against, ain, all, am, an, and, any, are, aren, aren't, as, at, be, because, been, before, being, below, between, both, but, by, can, couldn, couldn't, d, did, didn, didn't, do, does, doesn, doesn't, doing, don, don't, down, during, each, few, for, from, further, had, hadn, hadn't, has, hasn, hasn't, have, haven, haven't, having, he, he'd, he'll, her, here, hers, herself, he's, him, himself, his, how, i, i'd, if, i'll, i'm, in, into, is, isn, isn't, it, it'd, it'll, it's, its, itself, i've, just, ll, m, ma, me, mightn, mightn't, more, most, mustn, mustn't, my, myself, needn, needn't, no, nor, not, now, o, of, off, on, once, only, or, other, our, ours, ourselves, out, over, own, re, s, same, shan, shan't, she, she'd, she'll, she's, should, shouldn, shouldn't, should've, so, some, such, t, than, that, that'll, the, their, theirs, them, themselves, then, there, these, they, they'd, they'll, they're, they've, this, those, through, to, too, under, until, up, ve, very, was, wasn, wasn't, we, we'd, we'll, we're, were, weren, weren't, we've, what, when, where, which, while, who, whom, why, will, with, won, won't, wouldn, wouldn't, y, you, you'd, you'll, your, you're, yours, yourself, yourselves, you've

[nltk_data]   Unzipping corpora/stopwords.zip.

In [10]:
STOPWORDS = set(stopwords.words('english'))
len(STOPWORDS)

198

In [11]:
def remove_stopwords(text):
    return ' '.join([word for word in str(text).split(' ') if word not in STOPWORDS])

df["text_wo_stop"] = df["text_wo_punct"].apply(remove_stopwords)
df.head(10)

/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_99471/2529136276.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_wo_stop"] = df["text_wo_punct"].apply(remove_stopwords)

,text,text_lower,text_wo_punct,text_wo_stop
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...,applesupport causing reply disregarded tapped ...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...,105835 business means lot us please dm name zi...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...,virgintrains see attached error message ive tr...
5,"@105836 Have you tried from another device, Mi...","@105836 have you tried from another device, mi...",105836 have you tried from another device miri...,105836 tried another device miriam mm
6,"@VirginTrains yep, I've tried laptop too sever...","@virgintrains yep, i've tried laptop too sever...",virgintrains yep ive tried laptop too several ...,virgintrains yep ive tried laptop several time...
7,"@105836 It's working OK from here, Miriam. Doe...","@105836 it's working ok from here, miriam. doe...",105836 its working ok from here miriam does th...,105836 working ok miriam link help httpstco0m2...
8,@VirginTrains I still haven't heard &amp; the ...,@virgintrains i still haven't heard &amp; the ...,virgintrains i still havent heard amp the numb...,virgintrains still havent heard amp number im ...
9,@105836 That's what we're here for Miriam 😊 T...,@105836 that's what we're here for miriam 😊 t...,105836 thats what were here for miriam 😊 the ...,105836 thats miriam 😊 team send email shortly hp

#### Удаление частых слов

In [12]:
from collections import Counter
cnt = Counter()
for text in df["text_wo_stop"].values:
    for word in text.split():
        cnt[word] += 1

cnt.most_common(10)

[('us', 25),
 ('dm', 19),
 ('help', 18),
 ('thanks', 13),
 ('httpstcogdrqu22ypt', 12),
 ('applesupport', 11),
 ('please', 11),
 ('phone', 9),
 ('hi', 9),
 ('ive', 8)]

In [13]:
FREQWORDS = set([w for (w,s) in cnt.most_common(10)])

def remove_freqwords(text):
    return " ".join([word for word in str(text).split(" ") if word not in FREQWORDS])

df['text_wo_stop_freq'] = df["text_wo_stop"].apply(remove_freqwords)
df.head(10)

/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_99471/1990522747.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_wo_stop_freq'] = df["text_wo_stop"].apply(remove_freqwords)

,text,text_lower,text_wo_punct,text_wo_stop,text_wo_stop_freq
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...,applesupport causing reply disregarded tapped ...,causing reply disregarded tapped notification ...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...,105835 business means lot us please dm name zi...,105835 business means lot name zip code additi...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...,76328 really hope change im sure wont dont,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...,105836 livechat online moment httpstcosy94vtu...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...,virgintrains see attached error message ive tr...,virgintrains see attached error message tried ...
5,"@105836 Have you tried from another device, Mi...","@105836 have you tried from another device, mi...",105836 have you tried from another device miri...,105836 tried another device miriam mm,105836 tried another device miriam mm
6,"@VirginTrains yep, I've tried laptop too sever...","@virgintrains yep, i've tried laptop too sever...",virgintrains yep ive tried laptop too several ...,virgintrains yep ive tried laptop several time...,virgintrains yep tried laptop several times pa...
7,"@105836 It's working OK from here, Miriam. Doe...","@105836 it's working ok from here, miriam. doe...",105836 its working ok from here miriam does th...,105836 working ok miriam link help httpstco0m2...,105836 working ok miriam link httpstco0m2mph15...
8,@VirginTrains I still haven't heard &amp; the ...,@virgintrains i still haven't heard &amp; the ...,virgintrains i still havent heard amp the numb...,virgintrains still havent heard amp number im ...,virgintrains still havent heard amp number im ...
9,@105836 That's what we're here for Miriam 😊 T...,@105836 that's what we're here for miriam 😊 t...,105836 thats what were here for miriam 😊 the ...,105836 thats miriam 😊 team send email shortly hp,105836 thats miriam 😊 team send email shortly hp

#### Удаление редких слов

In [14]:
n_rare_words = 10
RAREWORDS = set([w for (w,s) in cnt.most_common()[:-n_rare_words-1:-1]])
RAREWORDS

{'browser',
 'green',
 'httpstco9281okeebk',
 'including',
 'keen',
 'lee',
 'line',
 'log',
 'slowdown',
 'thin'}

In [15]:
def remove_rarewords(text):
    return " ".join([word for word in str(text).split(" ") if word not in RAREWORDS])

df['text_wo_stop_freq_rare'] = df["text_wo_stop_freq"].apply(remove_rarewords)
df.head(10)

/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_99471/1472272191.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_wo_stop_freq_rare'] = df["text_wo_stop_freq"].apply(remove_rarewords)

,text,text_lower,text_wo_punct,text_wo_stop,text_wo_stop_freq,text_wo_stop_freq_rare
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...,applesupport causing reply disregarded tapped ...,causing reply disregarded tapped notification ...,causing reply disregarded tapped notification ...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...,105835 business means lot us please dm name zi...,105835 business means lot name zip code additi...,105835 business means lot name zip code additi...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...,76328 really hope change im sure wont dont,76328 really hope change im sure wont dont,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...,105836 livechat online moment httpstcosy94vtu...,105836 livechat online moment httpstcosy94vtu...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...,virgintrains see attached error message ive tr...,virgintrains see attached error message tried ...,virgintrains see attached error message tried ...
5,"@105836 Have you tried from another device, Mi...","@105836 have you tried from another device, mi...",105836 have you tried from another device miri...,105836 tried another device miriam mm,105836 tried another device miriam mm,105836 tried another device miriam mm
6,"@VirginTrains yep, I've tried laptop too sever...","@virgintrains yep, i've tried laptop too sever...",virgintrains yep ive tried laptop too several ...,virgintrains yep ive tried laptop several time...,virgintrains yep tried laptop several times pa...,virgintrains yep tried laptop several times pa...
7,"@105836 It's working OK from here, Miriam. Doe...","@105836 it's working ok from here, miriam. doe...",105836 its working ok from here miriam does th...,105836 working ok miriam link help httpstco0m2...,105836 working ok miriam link httpstco0m2mph15...,105836 working ok miriam link httpstco0m2mph15...
8,@VirginTrains I still haven't heard &amp; the ...,@virgintrains i still haven't heard &amp; the ...,virgintrains i still havent heard amp the numb...,virgintrains still havent heard amp number im ...,virgintrains still havent heard amp number im ...,virgintrains still havent heard amp number im ...
9,@105836 That's what we're here for Miriam 😊 T...,@105836 that's what we're here for miriam 😊 t...,105836 thats what were here for miriam 😊 the ...,105836 thats miriam 😊 team send email shortly hp,105836 thats miriam 😊 team send email shortly hp,105836 thats miriam 😊 team send email shortly hp

#### Стэминг

In [16]:
df = df.drop(["text_lower", "text_wo_punct", "text_wo_stop", "text_wo_stop_freq"], axis=1)

In [17]:
df.head(10)

,text,text_wo_stop_freq_rare
0,@AppleSupport causing the reply to be disregar...,causing reply disregarded tapped notification ...
1,@105835 Your business means a lot to us. Pleas...,105835 business means lot name zip code additi...
2,@76328 I really hope you all change but I'm su...,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,virgintrains see attached error message tried ...
5,"@105836 Have you tried from another device, Mi...",105836 tried another device miriam mm
6,"@VirginTrains yep, I've tried laptop too sever...",virgintrains yep tried laptop several times pa...
7,"@105836 It's working OK from here, Miriam. Doe...",105836 working ok miriam link httpstco0m2mph15...
8,@VirginTrains I still haven't heard &amp; the ...,virgintrains still havent heard amp number im ...
9,@105836 That's what we're here for Miriam 😊 T...,105836 thats miriam 😊 team send email shortly hp

In [18]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df["text_stemmed"] = df["text_wo_stop_freq_rare"].apply(stem_words)
df.head(10)

,text,text_wo_stop_freq_rare,text_stemmed
0,@AppleSupport causing the reply to be disregar...,causing reply disregarded tapped notification ...,caus repli disregard tap notif keyboard opened😡😡😡
1,@105835 Your business means a lot to us. Pleas...,105835 business means lot name zip code additi...,105835 busi mean lot name zip code addit detai...
2,@76328 I really hope you all change but I'm su...,76328 really hope change im sure wont dont,76328 realli hope chang im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,105836 livechat online moment httpstcosy94vtu...,105836 livechat onlin moment httpstcosy94vtu8k...
4,@VirginTrains see attached error message. I've...,virgintrains see attached error message tried ...,virgintrain see attach error messag tri leav v...
5,"@105836 Have you tried from another device, Mi...",105836 tried another device miriam mm,105836 tri anoth devic miriam mm
6,"@VirginTrains yep, I've tried laptop too sever...",virgintrains yep tried laptop several times pa...,virgintrain yep tri laptop sever time past wee...
7,"@105836 It's working OK from here, Miriam. Doe...",105836 working ok miriam link httpstco0m2mph15...,105836 work ok miriam link httpstco0m2mph15eh mm
8,@VirginTrains I still haven't heard &amp; the ...,virgintrains still havent heard amp number im ...,virgintrain still havent heard amp number im d...
9,@105836 That's what we're here for Miriam 😊 T...,105836 thats miriam 😊 team send email shortly hp,105836 that miriam 😊 team send email shortli hp

#### Обработка русского языка

In [19]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer('russian')
wrds = ["первый", 'день', 'осенний', 'годы', 'время', 'лето']
for w in wrds:
    print(stemmer.stem(w))

перв
ден
осен
год
врем
лет