## Анализ набора данных с использованием `pandas`

### Загрузка данных и первичный обзор

В этом задании мы будем работать с набором данных `gapminder`, который содержит информацию о различных странах и их показателях развития. Мы будем использовать библиотеку Pandas для базового анализа данных.

In [2]:
import pandas as pd
gapminder_data = pd.read_csv('gapminder.csv')

Выведите информацию о первых 10 записях набора данных:

In [3]:
gapminder_data.head(10)

,country,region,income,income_level,life_exp,co2,co2_change,population
0,Afghanistan,Asia,2.03,Level 1,62.7,0.254,increase,37.2000
1,Albania,Europe,13.30,Level 3,78.4,1.590,increase,2.8800
2,Algeria,Africa,11.60,Level 3,76.0,3.690,increase,42.2000
3,Andorra,Europe,58.30,Level 4,82.1,6.120,decrease,0.0770
4,Angola,Africa,6.93,Level 2,64.6,1.120,decrease,30.8000
5,Antigua and Barbuda,Americas,21.00,Level 3,76.2,5.880,increase,0.0963
6,Argentina,Americas,22.70,Level 3,76.5,4.410,decrease,44.4000
7,Armenia,Europe,12.70,Level 3,75.6,1.890,decrease,2.9500
8,Australia,Asia,49.00,Level 4,82.9,16.900,decrease,24.9000
9,Austria,Europe,55.30,Level 4,82.1,7.750,decrease,8.8900

Выведите информацию о количестве записей и столбцов в наборе данных:

In [4]:
gapminder_data.shape

(193, 8)

Произведите группировку данных по региону сохраните значение в переменной `region_means` содержащей усредненные значения по показателям `income`, `life_exp`, `co2`, `population`:

In [6]:
region_means = gapminder_data.groupby('region')[['income', 'life_exp', 'co2', 'population']].mean()
region_means

             income   life_exp       co2  population
region
Africa     5.733426  65.277778  1.213459   23.597094
Americas  18.022857  75.240000  4.204057   28.597837
Asia      20.477627  72.779661  6.282186   76.264483
Europe    38.120000  78.866667  6.344000   18.812778

In [7]:
region_means = gapminder_data.pivot_table(index='region', values=['income', 'life_exp', 'co2', 'population'])
region_means

               co2     income   life_exp  population
region
Africa    1.213459   5.733426  65.277778   23.597094
Americas  4.204057  18.022857  75.240000   28.597837
Asia      6.282186  20.477627  72.779661   76.264483
Europe    6.344000  38.120000  78.866667   18.812778

Отобразите список уникальных регионов, присутствующих в данных:

In [8]:
region_means.index.to_list()

['Africa', 'Americas', 'Asia', 'Europe']

In [ ]:
# gapminder_data['region'].unique()
# gapminder_data['region'].drop_duplicates()
# gapminder_data.drop_duplicates(subset='region')['region']

0        Asia
1      Europe
2      Africa
5    Americas
Name: region, dtype: object

Выведите список стран, входящих в регион 'Europe':

In [12]:
gapminder_data[gapminder_data['region'] == 'Europe']['country'].unique()

array(['Albania', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan',
       'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria',
       'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia',
       'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary',
       'Iceland', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia',
       'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia',
       'Slovak Republic', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
       'Turkey', 'Ukraine', 'United Kingdom'], dtype=object)

Найдите медианное значение продолжительности жизни ('life_exp') по региону 'Africa':

In [13]:
gapminder_data[gapminder_data['region'] == 'Africa']['life_exp'].mean()

65.27777777777777

In [14]:
df = gapminder_data
median = df[df['region'] == 'Africa']['life_exp'].median()
print(median)

64.7

Найдите страну с наибольшим количеством выбросов CO2 ('co2').

In [15]:
gapminder_data.sort_values('co2', ascending=False)['country'].to_list()[0]

'Qatar'

Создайте новый столбец 'income_category', который будет содержать значения 'low', 'medium' и 'high' в зависимости от уровня дохода ('income').

In [17]:
low = gapminder_data['income'].quantile(0.2)
high = gapminder_data['income'].quantile(0.8)

In [18]:
print(low, high)

3.7340000000000004 35.28000000000001

In [19]:
def categorize_income(income):
    if income < low:
        return 'low'
    elif income < high:
        return 'medium'
    else:
        return 'high'


gapminder_data['income_category'] = gapminder_data['income'].apply(categorize_income)

gapminder_data[['country', 'income', 'income_category']]

         country  income income_category
0    Afghanistan    2.03             low
1        Albania   13.30          medium
2        Algeria   11.60          medium
3        Andorra   58.30            high
4         Angola    6.93          medium
..           ...     ...             ...
188    Venezuela   12.40          medium
189      Vietnam    7.59          medium
190        Yemen    2.66             low
191       Zambia    3.52             low
192     Zimbabwe    3.92          medium

[193 rows x 3 columns]

Посчитайте общее население (`population`) по региону `Americas`:

In [20]:
gapminder_data[gapminder_data['region'] == 'Americas']['population'].sum()

1000.9243